rbm_website/apps/rbm/urls.py
from django.conf.urls import patterns, include, url
from rbm_website.apps.rbm import views

# URLs for the RBM website
urlpatterns = patterns('',
    url(r'^$', views.dbn_list, name='index'),
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<pk>\d+)/$', views.DBNDetailView.as_view(), name='view'),
    url(r'^(?P<dbn_id>\d+)/train/$', views.train, name='train'),
    url(r'^(?P<dbn_id>\d+)/delete/$', views.delete, name='delete'),
    url(r'^training/$', views.training, name='training'),
    url(r'^(?P<dbn_id>\d+)/classify/$', views.classify, name='classify')
)

rbm_website/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

# The Django Admin URLs
admin.autodiscover()

# All the URLs available to the application
urlpatterns = patterns('',
    url(r'^$', 'rbm_website.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^faq/$', 'rbm_website.views.faq', name='faq'),
    url(r'^rbm/', include('rbm_website.apps.rbm.urls')),
    url(r'^users/', include('rbm_website.apps.users.urls')),
    url(r'^accounts/logout/', 'rbm_website.apps.users.views.user_logout'),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'users/login.html'}),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^tutorial/$', 'rbm_website.views.tutorial', name='tutorial')
)

rbm_website/apps/rbm/models.py
from django.db import models
from django.contrib.auth.models import User
from picklefield.fields import PickledObjectField
from rbm_website.libs.rbm_lib.dbn import DBN

# The DBN model object
# Contains the name and other key details
# Contains a pickled object of the dbn
# Contains the list of labels
# Provides some methods for manipulation
class DBNModel(models.Model):
    name = models.CharField(max_length=200)
    creator = models.ForeignKey(User, related_name='dbns')
    created = models.DateTimeField(auto_now_add=True)
    description = models.CharField(max_length=1000)
    height = models.IntegerField(max_length=10)
    width = models.IntegerField(max_length=10)
    labels = models.IntegerField(max_length=10)
    private = models.BooleanField()
    training = models.BooleanField()
    trained = models.BooleanField()
    dbn = PickledObjectField()
    label_values = PickledObjectField()

    # The string representation of the DBN
    def __unicode__(self):
        return (self.name + " - " + self.creator.username)

    # Gets the DBN topology
    def get_topology(self):
        return self.dbn.get_topology()

    # Classifies an image using the DBN
    def classify_image(self, image_data, samples):
        return self.dbn.classify(image_data, samples)

    # Creates a DBN with given parameters
    @staticmethod
    def build_dbn(name, creator, description, height, width, config, labels, private, learning_rate):
        dbn = DBN(config, labels, learning_rate)
        return DBNModel(name=name, creator=creator, description=description, height=height,
            width=width, labels=labels, private=private, training=False, trained=False, dbn=dbn)

rbm_website/apps/rbm/forms.py
from django import forms

# The search form
# Provides the options for searching and sorting DBNs
class SearchForm(forms.Form):
    criteria = forms.CharField(initial='Enter search criteria...', max_length=200)
    trained = forms.BooleanField(required=False)
    SORTS = (
        ("namedesc", ("Name (A-Z)")),
        ("nameasc", ("Name (Z-A)")),
        ("timedesc", ("Date Added (Recent)")),
        ("timeasc", ("Data Added (Oldest)")),
    )
    order_by = forms.ChoiceField(choices=SORTS)

# The form to create the DBN
# Provides all of the labels allowed to be used
class DBNForm(forms.Form):
    name =  forms.CharField(max_length=200)
    description = forms.CharField(max_length=1000, widget=forms.Textarea)
    height = forms.IntegerField(initial=28)
    width = forms.IntegerField(initial=28)
    labels = forms.IntegerField()
    learning_rate = forms.FloatField(initial=0.1)
    private = forms.BooleanField(required=False, help_text='Check if you want a private DBN')
    layer_count = forms.IntegerField(widget = forms.HiddenInput())

    # Creates the form initially
    # Dynamically adds layers when needed
    def __init__(self, *args, **kwargs):
        layers = kwargs.pop('layer', 0)

        super(DBNForm, self).__init__(*args, **kwargs)
        self.fields['layer_count'].initial = layers

        for index in range(int(layers)):
            self.fields['layer_{index}'.format(index=index)] = forms.IntegerField()

    # Cleans the height field of the DBN
    def clean_height(self):
        data = self.cleaned_data['height']
        if (not(0 < data <= 30)):
            raise forms.ValidationError("Height must be a positive integer, maximum of 30!")
        return data

    # Cleans the width field of the DBN
    def clean_width(self):
        data = self.cleaned_data['width']
        if (not(0 < data <= 30)):
            raise forms.ValidationError("Width must be a positive integer, maximum of 30!")
        return data

    # Cleans the labels field of the DBN
    def clean_labels(self):
        data = self.cleaned_data['labels']
        if (data <= 0):
            raise forms.ValidationError("Labels must be a positive integer!")
        return data

    # Cleans the learning rate field of the DBN
    def clean_learning_rate(self):
        data = self.cleaned_data['learning_rate']
        if (data <= 0):
            raise forms.ValidationError("Learning rate must be a positive float!")
        return data

rbm_website/apps/rbm/views.py
import os
import json
import shutil
import tasks
import numpy as np
from PIL import Image as pil
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.conf import settings
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib import messages
from rbm_website.apps.rbm.forms import DBNForm
from rbm_website.apps.rbm.forms import SearchForm
from rbm_website.apps.rbm.models import DBNModel
from rbm_website.libs.image_lib import image_processor as imgpr
from rbm_website.libs.decorators import message_login_required

# Generic view for a list of DBNs
class DBNListView(ListView):
    model = DBNModel

    @method_decorator(message_login_required)
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DBNListView, self).dispatch(*args, **kwargs)

# Generic view for the profile of a DBN
class DBNDetailView(DetailView):
    model = DBNModel

    def get_context_data(self, **kwargs):
        context = super(DBNDetailView, self).get_context_data(**kwargs)
        context['topology'] = self.object.get_topology()

        # Gets the base images if trained
        if self.object.trained:
            class_path = settings.MEDIA_ROOT + str(self.object.id)
            base_path = class_path + '/base_images'
            (images, labels) = imgpr.retrieve_images_base64(base_path)
            dictionary = dict(zip(labels, images))
            context['image_data'] = dictionary

        return context

    # Checks to make sure that only those allowed can access the DBN
    @method_decorator(message_login_required)
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        dbn = self.get_object()
        if (dbn.private and (self.request.user != dbn.creator)):
            messages.add_message(self.request, messages.ERROR, 'That DBN is private and you are not the owner!')
            url = reverse('index')
            return redirect(url)
        else:
            return super(DBNDetailView, self).dispatch(*args, **kwargs)

# Gets a list of DBNs
# By default, returns the 10 most recent DBNs
# Otherwise allows the user to search and sort DBNs
# Provides the base image or a default image if not trained
@message_login_required
@login_required
def dbn_list(request):
    if request.method == 'GET':
        form = SearchForm()
        recent_dbns = DBNModel.objects.filter(private=False).order_by('-created')[:10]
        dbn_images = []
        for dbn in recent_dbns:
            if dbn.trained:
                class_path = settings.MEDIA_ROOT + str(dbn.id)
                image_path = class_path + '/base_images/' + dbn.label_values[0] + '.png'
                image = imgpr.retrieve_image_base64(image_path)
                dbn_images.append(image)
            else:
                dbn_images.append('notTrained')
        dbn_info = zip(recent_dbns, dbn_images)
        return render(request, 'rbm/dbnmodel_list.html', {'dbns': dbn_info, 'searchForm' : form})
    elif request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            criteria = form.cleaned_data['criteria']
            order = form.cleaned_data['order_by']
            trained_only = form.cleaned_data['trained']
            terms = criteria.split()
            result_dbns = []
            dbn_images = []

            for t in terms:
                if trained_only:
                    termResults = DBNModel.objects.filter(name__icontains=t).filter(private=False).filter(trained=True)
                else:
                    termResults = DBNModel.objects.filter(name__icontains=t).filter(private=False)
                for tResult in termResults:
                    if (not tResult in result_dbns):
                        result_dbns.append(tResult)

                creatorResults = User.objects.filter(username__icontains=t)
                for cResult in creatorResults:
                    if trained_only:
                        cDbns = cResult.dbns.filter(private=False).filter(trained=True)
                    else:
                        cDbns = cResult.dbns.filter(private=False)
                    for dbn in cDbns:
                        if (not dbn in result_dbns):
                           result_dbns.append(dbn)

                if t.isdigit():
                    searchID = int(t)
                    if trained_only:
                        idResults = DBNModel.objects.filter(id__exact=searchID).filter(private=False).filter(trained=True)
                    else:
                        idResults = DBNModel.objects.filter(id__exact=searchID).filter(private=False)
                    for iResult in idResults:
                        if (not iResult in result_dbns):
                            result_dbns.append(iResult)

            if order == "nameasc":
                result_dbns.sort(key=lambda x: x.name, reverse=True)
            elif order == "namedesc":
                result_dbns.sort(key=lambda x: x.name)
            elif order == "timeasc":
                result_dbns.sort(key=lambda x: x.created)
            elif order == "timedesc":
                result_dbns.sort(key=lambda x: x.created, reverse=True)

            for dbn in result_dbns:
                if dbn.trained:
                    class_path = settings.MEDIA_ROOT + str(dbn.id)
                    image_path = class_path + '/base_images/' + dbn.label_values[0] + '.png'
                    image = imgpr.retrieve_image_base64(image_path)
                    dbn_images.append(image)
                else:
                    dbn_images.append('notTrained')

            dbn_info = zip(result_dbns, dbn_images)
            return render(request, 'rbm/dbnmodel_list.html', {'dbns': dbn_info, 'searchForm' : form})
        else:
            return render(request, 'rbm/dbnmodel_list.html', {'searchForm' : form})
    else:
        return render(request, 'rbm/dbnmodel_list.html', {})

# Deletes a DBN from the database
# Checks to make sure only the creator can delete the DBN
@message_login_required
@login_required
def delete(request, dbn_id):
    if request.method == 'GET':
        dbn = get_object_or_404(DBNModel , pk=dbn_id)

        if dbn.creator == request.user:
            dbn.delete()
            messages.add_message(request, messages.INFO, 'Your DBN was successfully deleted!')
            url = reverse('home')
            return redirect(url)
        else:
            messages.add_message(request, messages.INFO, 'You do not have permission to delete this DBN!')
            url = reverse('view', kwargs={'pk': dbn.id})
            return redirect(url)
    else:
        url = reverse('home')
        return redirect(url)

# Classifies an image using the DBN
# Flips the pixels if required
# Gets the image posted
# Classifies it and then returns the probability via a JSON
# Used as an AJAX request
# Otherwise just returns the classify page
def classify(request, dbn_id):
    if request.method == 'POST':
        dbn = get_object_or_404(DBNModel , pk=dbn_id)
        save_image("classifyImage", request.POST['image_data'], dbn)
        image_data = imgpr.convert_url_to_array(request.POST['image_data'], "classifyImage")

        if dbn.id in settings.FLIPPED_DBNS:
            iterator = np.vectorize(flip_pixels)
            image_data = iterator(image_data)

        probs = dbn.classify_image([image_data], 1)
        for i in range(1,10):
            probs = probs + dbn.classify_image([image_data], 1)

        probs = probs[0] / 10
        max_prob = probs.max()
        result = dbn.label_values[probs.argmax(axis=0)]

        os.remove(settings.MEDIA_ROOT + str(dbn.id) + '/base_images/classifyImage.png')

        json_data = json.dumps({
            "label_values": dbn.label_values,
            "probs":probs.tolist(),
            "max_prob":max_prob,
            "result":result
        })

        return HttpResponse(json_data, mimetype="application/json")
    else:
        if not request.user.is_authenticated():
            messages.add_message(request, messages.ERROR, "You must be logged in to access this content!")
            url = reverse('home', kwargs={})
            return redirect(url)
        else:
            dbn = get_object_or_404(DBNModel , pk=dbn_id)

            if dbn.training:
                messages.add_message(request, messages.ERROR, 'This DBN is currently being trained!' +
                    ' Please check back shortly to use it!')
                url = reverse('view', kwargs={'pk': dbn.id})
                return redirect(url)

            return render(request, 'rbm/classify.html', {'dbn': dbn})

# Flips a pixel
def flip_pixels(value):
    if value == 1:
        return 0
    else:
        return 1

# Trains the DBN
# Gets the images and labels posted
# Starts the celery task to train in the background
# Otherwise returns the training page to begin training
@message_login_required
@login_required
def train(request, dbn_id):
    if request.method == 'POST':
        dbn = get_object_or_404(DBNModel , pk=dbn_id)

        clean_image_directory(dbn.id)
        label_values = []

        for x in range(0, dbn.labels):
            save_image(request.POST['classImages[' + str(x) + '][image_name]'],
                request.POST['classImages[' + str(x) + '][image_data]'], dbn)
            label_values.append(request.POST['classImages[' + str(x) + '][image_name]'])


	pre_epoch = int(request.POST.get('pre_epoch'))
	train_epoch = int(request.POST.get('train_epoch'))
	train_loop = int(request.POST.get('train_loop'))
        tasks.train_dbn.delay(dbn, label_values, pre_epoch, train_epoch, train_loop)
        messages.add_message(request, messages.INFO, 'Congratulations! Your DBN is training.' +

rbm_website/apps/rbm/templates/rbm/classify.html
{% extends "base.html" %}
{% load staticfiles %}

{% block scripts %}
    <script src="{% static 'rbm/js/pixel_drawer.js' %}"></script>
{% endblock %}

{%block title%}
{{dbn.name}} Classifier
{% endblock %}

{% block content %}

<h1> {{dbn.name}} Classifier </h1>
<hr style="background-color: #000000;border-color: #000000"/>
<div style="margin: 20px 0">
    Here, you can draw and submit images which this deep belief network will attempt to classify. The results will be displayed in the table on
    the right, showing the probabilities of each class as well as the most likely result.
    <br><br>
    It might not always get the right result, but if it was trained on a reasonable set of input data and the images you draw are similar to those
    it was trained on, there is around an <span style="font-weight:bold">80%</span> chance that it will obtain the correct result.
    <br><br>
    Please draw your images using the drawing tool provided and when you are ready, click classify to see the result. You can do this as many
    times as you want. It may be useful to centre the image before submitting to improve the results.
</div>
<hr style="background-color: #000000;border-color: #000000"/>

<div id="drawerContainer">
    <h2>Drawing Tool:</h2>
    <div id="pixelDrawerContainer">
    </div>

    <div id="commands">
        <div id="brushContainer">
            <button id="brush" class="btn draw-btn" type="button">
                <img src="{% static 'libs/img/brush.png' %}" alt="BRUSH">
            </button>
        </div>
        <div id="eraserContainer">
            <button id="eraser" class="btn draw-btn" type="button">
                <img src="{% static 'libs/img/eraser.png' %}" alt="ERASER">
            </button>
        </div>
        <div id="smallContainer">
            <button id="small" class="btn draw-btn" type="button">
                <img src="{% static 'libs/img/small.png' %}" alt="SMALL">
            </button>
        </div>
        <div id="mediumContainer">
            <button id="medium" class="btn draw-btn" type="button">
                <img src="{% static 'libs/img/medium.png' %}" alt="MEDIUM">
            </button>
        </div>
        <div id="largeContainer">
            <button id="large" class="btn draw-btn" type="button">
                <img src="{% static 'libs/img/large.png' %}" alt="LARGE">
            </button>
        </div>
        <div id="clearContainer">
            <button id="clear" class="btn draw-btn" type="button">
                <img src="{% static 'libs/img/clear.png' %}" alt="CLEAR">
            </button>
        </div>
        <div id="centreContainer">
            <button id="centre" class="btn draw-btn" type="button">
                <img src="{% static 'libs/img/centre.png' %}" alt="CENTRE">
            </button>
        </div>
    </div>
</div>

<div id="controlContainer">
    <h2>Results:</h2>
    <div id="classifyButtonContainer" style="margin:20px 0px;">
        <button id="classifyButton" type="button" class="btn btn-success btn-sm">Classify <i class="glyhpicon glyphicon-upload"></i></button>
        Most Likely Class: <span id="maxProbContainer" style="color: #0E9A25; font-weight: bold"></span>
    </div>

    <div id="results">
        <div id="probabilities">
            <div id="probs-table">
                <div class="probs-table-head">
                    <table class="light-table" style="width: 300px" cellpadding="0" cellspacing="0">
                      <tr>
                        <th width="40%"><b>Label</b></th>
                        <th width="60%"><b>Probability</b></th>
                      </tr>
                    </table>
                </div>

                <div style="overflow-x: hidden; overflow-y: auto;height: 250px; width: 315px;">
                    <div class="probs-table-data">
                        <table class="light-table" style="width: 300px;border-collapse:collapse;" cellpadding="0" cellspacing="0">

                        {% for label in dbn.label_values %}
                            {% with divName=label|add:"LabelContainer" %}
                            <tr>
                                <td style="border-collapse: collapse;" width="40%">{{ label }}</td>
                                <td style="border-collapse: collapse;" width="60%"><span id="{{divName}}"></span></td>
                            </tr>
                            {% endwith %}
                        {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
</div>

<script>
    pixelDrawer = new PixelDrawer($('#pixelDrawerContainer'), {{dbn.width}}, {{dbn.height}}, "classify", {{dbn.labels}}, "{% url 'classify' dbn.id %}", '{{csrf_token}}');
</script>

{% endblock %}

rbm_website/apps/rbm/templates/rbm/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block scripts %}
    <script src="{% static 'rbm/js/visualiser.js' %}"></script>
{% endblock %}

{%block title%}
Create DBN
{% endblock %}

{% block content %}

<h1>Create a DBN!</h1>
<hr style="background-color: #000000;border-color: #000000"/>
<p>
Here, you can create your own deep belief network! To do so, please fill in the form below with the appropriate data.
We have set the values for the learning rate, image height and image width to appropriate defaults but feel free to change
them to suit your project.
</p>
<br>
<br>
<p>
Don't forget to add additional layers to make sure your DBN can classify effectively. If you are unsure of what values to use,
you can read up about the layers in our tutorial section. A good topology to use is <span style="font-weight: bold">(Input <-> 500 <-> 500 <-> 2000 <-> Labels)</span>
but again, feel free to use your own. You can preview your topology which will adjust automatically according to your values.
</p>
<hr style="background-color: #000000;border-color: #000000"/>
<br>
<br>

<div id="formContainer">
    <h3>DBN Attributes:</h3>
    <br>
    <form class="form-horizontal" action="{% url 'create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        <div class="fieldWrapper">
            <label for="id_name" class="text-center">Name:</label>
            <br>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <br>
        <div class="fieldWrapper">
            <label for="id_description">Description:</label>
            <br>
            {{ form.description }}
            {{ form.description.errors }}
        </div>
        <br>
        <div class="fieldWrapper">
            <label for="id_private">Private DBN:</label>
            {{ form.private }}
            {{ form.private.errors }}
        </div>
        <br>
        <div class="fieldWrapper">
            <label for="id_learning_rate">Learning Rate:</label>
            <br>
            {{ form.learning_rate }}
            {{ form.learning_rate.errors }}
        </div>
        <br>
        <div class="fieldWrapper">
            <label for="id_height">Image Height:</label>
            <br>
            {{ form.height }}
            {{ form.height.errors }}
        </div>
        <br>
        <div class="fieldWrapper">
            <label for="id_width">Image Width:</label>
            <br>
            {{ form.width }}
            {{ form.width.errors }}
        </div>
        <br>
        <div id="layers">
            <h4>Layers:</h4>
            {% for field in form.visible_fields %}
                {% if "Layer" in field.label %}
                    <div class="fieldWrapper">
                        {{ field.label_tag }} {{ field }}
                        {{ field.errors }}
                    </div>
                    <br>
                {% endif %}
            {% endfor %}
        </div>
        <br>
        <div class="fieldWrapper">
            <label for="id_labels">No. Labels:</label>
            <br>
            {{ form.labels }}
            {{ form.labels.errors }}
        </div>

        <br><br>
        <button type = "button" id="add-layer" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Add Layer</button>
        <button type = "button" id="delete-layer" class="btn btn-primary"><span class="glyphicon glyphicon-minus"></span> Delete Layer</button>
        <button type = "button" id="preview" class="btn btn-info"><span id="previewIcon" class="glyphicon glyphicon-stop"></span> <span id="previewStatus">Stop preview<span></button>
        <br>
        <br>
        <button class="btn btn-success"><i class="glyphicon glyphicon-ok"></i> Create DBN</button>
    </form>
</div>

<div id="canvasContainer" class="preview-canvas">
    <h3>Topology Preview:</h3>
    <br>
</div>

{% endblock %}

{% block create_link_class %} class="active" {% endblock %}

rbm_website/apps/rbm/templates/rbm/dbnmodel_detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block scripts %}
    <script src="{% static 'rbm/js/topology.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var topology = getTopology();
            var layerCount = {{object.dbn.number_layers}}
            preview(topology, layerCount);
            prevInterval = setInterval(function() {
                preview(topology, layerCount);
            }, 1000);
        });

        function getTopology() {
            var topology = new Array();
            var i = 0;
            {% for t in topology %}
                topology[i] = {{ t }};
                i++
            {% endfor %}
            return topology;
        };
    </script>
{% endblock %}

{%block title%}
{{object.name}}
{% endblock %}

{% block content %}

<div class="profile-details">

    <div id="dbn-details">
        <p class="dbn-title">DBN Name: {{object.name}}</p>

        <p class="dbn-creator">
            Created by <a href="{% url 'view_user' object.creator.username %}">{{ object.creator.username }}</a>
            {% if object.private %}
                (<span class="private-dbn">Private</span>)
            {% else %}
                (<span class="public-dbn">Public</span>)
            {% endif %}
            on <span class="dbn-date">{{object.created}}</span>
        </p>

        <br>
        <div class="dbn-description">
            <h4>Description:</h4>
            <br>
            {{object.description}}
        </div>
        <br>

        <p class="dbn-status">
            {% if object.trained %}
                This DBN has been trained and is ready to classify <a href="{% url 'classify' object.id %}">here</a>!
            {% else %}
                {% if object.training %}
                    This DBN is currently training! Please check back shortly to use it.
                    <div id="detail-spinner" class="centre-div">
                        <div class="bubblingGSmall">
                            <span id="bubblingGSmall_1">
                            </span>
                            <span id="bubblingGSmall_2">
                            </span>
                            <span id="bubblingGSmall_3">
                            </span>
                        </div>
                    </div>
                {% else %}
                    This DBN has not started training yet, please check back later to see if its owner has trained it. Until then feel free to search for a trained DBN to test and use!
                {% endif %}
            {% endif %}
        </p><br>

        {% if object.trained %}
            <p class="dbn-config">
                This DBN takes pictures of size {{object.width}}x{{object.height}} and classifies them into one of the following {{object.labels}}
                {% if object.labels == 1 %}
                    label!
                {% else %}
                    labels!
                {% endif %}

                <div class="class-image-container" style="width: 400px;">
                        {% for label, image in image_data.items %}
			    <div class="class-image-row" style="width: 50%; float: {% cycle 'left' 'right' %};">
                                <div class="class-image-label">
                                    {{ label }}
                                </div>
                                <div class=class-image>
                                    <img alt="Thumbnail" style="margin: 5px 0; border: 1px solid #000000;" width="{{object.width}}" height="{{object.height}}" src="data:image/png;base64,{{image}}"/>
                                </div>
                            </div>
                        {% endfor %}
                </div>

            </p>
        {% endif %}

        {% if object.creator.username == user.username %}
            <div class="dbn-2" style="float: left">
            <h4>DBN Options:</h4>
            <p class="dbn-options">
                {{object.creator.username}}, as the creator of this DBN you can <a href="{% url 'delete' object.id %}">delete</a> or <a href="{% url 'train' object.id %}">train</a> this DBN.<br><br>
            </p>
            </div>
        {% endif %}
    </div>
</div>

<div id="canvasContainer" class="preview-canvas detail-preview-canvas">
    <h3>Topology Preview:</h3>
    <br>
</div>

{% endblock %}

rbm_website/apps/rbm/templates/rbm/dbnmodel_list.html
{% extends "base.html" %}
{% load staticfiles %}

{%block title%}
List
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            var clicked = false;
            $('#id_criteria').click(function () {
                if (!clicked) {
                    clicked = true;
                    $('#id_criteria').val('');
                }
            });
        });
    </script>
{% endblock %}

{% block content %}

<br>
<h2>List of Deep Belief Networks:</h2>
<br>

<p style="margin: 10px 0">
By default, this list shows the ten most recently added DBNs along with an image from their training sets if they are trained.
<br>
<br>
You can search for specific DBNs using the search bar. Your criteria will be matched against the name of the DBN, the creator and it's unique ID number.
<br>
<br>
<span style="font-weight: bold">Note:</span> Private DBNs will not appear in the list!
</p>
<hr style="background-color: #000000;border-color: #000000"/>
<br>
<form method="post" action=".">
    <div id="search-form">
        {% csrf_token %}

        {{ searchForm.criteria }}

        <span class="search-labels">Ordered by:</span> {{ searchForm.order_by }}

        <span class="search-labels">Trained DBNs Only:</span> {{ searchForm.trained }}

        <div style="margin-top: 15px">
            <button class="btn btn-sm">Search <i class="glyphicon glyphicon-search"></i></button>
        </div>
    </div>
</form>
<hr style="background-color: #000000;border-color: #000000"/>
<br>
<h2>Search Results:</h2>
<br>
<table class="dbn-list-table">
{% for dbn, image in dbns %}
    <tr>
        <td>
            {{dbn.id}}:
        </td>
        <td>
            {% if image == "notTrained" %}
                <img height="40" width="40" style="border-style:solid; border-width:1px; border-color:#000;" src="{% static 'libs/img/notTrained.png' %}" alt="NOTTRAINED">
            {% else %}
                <img alt="Thumbnail" width="40" height="40" style="border-style:solid; border-width:1px; border-color:#000;" src="data:image/png;base64,{{image}}"/>
            {% endif %}
        </td>
        <td>
            <a href="{% url 'view' dbn.id %}"> {{dbn.name}} </a> created by <a href="{% url 'view_user' dbn.creator.username %}">{{dbn.creator.username}}</a>
            Created on {{dbn.created}}
        </td>
    </tr>
{% endfor %}
</table>


{% endblock %}

{% block list_link_class %} class="active" {% endblock %}

rbm_website/apps/rbm/templates/rbm/view.html
<h2> {{name}} </h2>
<p>
Matrix: {{matrix}} 
</p>

<a href="{% url 'index' %}"> Index </a>